### ISSUE TITLE
Packager issues on Azure DevOps CI 

### ISSUE THREAD

**Issue by malcolmardalon** [getsimeon/IntuneAppBuilder#5]
Hi Simeon, I am able to use your code on my local machine without a problem however when I run the exact same pack command on an Azure DevOps build agent (running the default MS provided vm-2019 image)  there appears to be an exception: System.Runtime.InteropServices.COMException (0x80004005):   I was wondering if you could help, I would really appreciate it as I cannot use Microsofts own IntuneWinAppUtil.exe on CI build agents either.

You can invoke the tool using the following command: IntuneAppBuilder
Tool 'intuneappbuilder.console' (version '1.3.22') was successfully installed.
Solution Root is + D:\a\1\s
info: IntuneAppBuilder.Services.IntuneAppPackagingService[0]
      Creating Intune app package from D:\a\1\s\Apps\7-Zip\Input.
info: IntuneAppBuilder.Services.IntuneAppPackagingService[0]
      Creating intermediate zip of D:\a\1\s\Apps\7-Zip\Input at C:\Users\VssAdministrator\AppData\Local\Temp\Input.intunewin.zip.
info: IntuneAppBuilder.Services.IntuneAppPackagingService[0]
      Generating encrypted version of C:\Users\VssAdministrator\AppData\Local\Temp\Input.intunewin.zip.
Unhandled exception: System.IO.InvalidDataException: The specified Windows Installer file could not be opened. Verify the file is a valid Windows Installer file.
 ---> System.Runtime.InteropServices.COMException (0x80004005): OpenDatabase,DatabasePath,OpenMode
   at IntuneAppBuilder.Util.ComObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) in d:\a\1\s\Source\IntuneAppBuilder\Util\ComObject.cs:line 92
   at CallSite.Target(Closure , CallSite , Object , String , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at IntuneAppBuilder.Util.MsiUtil..ctor(String path, ILogger logger) in d:\a\1\s\Source\IntuneAppBuilder\Util\MsiUtil.cs:line 42
   --- End of inner exception stack trace ---
   at IntuneAppBuilder.Util.MsiUtil..ctor(String path, ILogger logger) in d:\a\1\s\Source\IntuneAppBuilder\Util\MsiUtil.cs:line 46
   at IntuneAppBuilder.Services.IntuneAppPackagingService.GetMsiInfo(String setupFilePath) in d:\a\1\s\Source\IntuneAppBuilder\Services\IntuneAppPackagingService.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by admin-simeon** [comment]
@malcolmardalon 

What vmImage do you have in your pool in your yml? 

vmImage: 'windows-latest'?

Just checking that first. 

Also, how is your msi file getting downloaded on the build agent? Can you add a step that runs

dir D:\a\1\s\Apps\7-Zip\Input

To your pipeline yml? If you could post your whole pipeline yml that would be helpful too

**Comment by malcolmardalon** [comment]
7-Zip MSI and Icon are files in the Github repo I'm using (I originally downloaded them from 7-Zips website).  I don't think Git is doing anything weird to the files b/c when I tested locally i cloned the repo to make sure and it worked.

dir output:
```
Directory: D:\a\1\s\Apps\7-Zip\Input

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           8/16/2020  9:01 PM            132 7z1900-x64.msi

```

azure-pipelines.yml:
```
# Documentation link: https://aka.ms/yaml

trigger:
  - main
  - master

variables:
  TENANT_ID: $(TenantId)
  TENANT_NAME: $(TenantName)
  CLIENT_ID: $(ClientId)
  CLIENT_SECRET: $(ClientSecret)
  SCOPE_: $(Scope)
  GRANT_TYPE: $(GrantType)

pool:
    vmImage: 'windows-2019'
  
steps:
  - pwsh: >
      dotnet tool install -g IntuneAppBuilder.Console ;
      $solutionRoot = $pwd.Path ; write-host "Solution Root is" + $solutionRoot ;
      $SourceFolder = "$solutionRoot\Apps\7-Zip\Input" ; 
      $SetupFile = "7z1900-x64.msi" ; 
      $OutputFolder = "$solutionRoot\Apps\7-Zip" ; 
      IntuneAppBuilder pack --source $SourceFolder --output $OutputFolder ;
      ls $SourceFolder
    displayName: "Test Different Packager"`
```

**Comment by admin-simeon** [comment]
That was my next thought - that git is messing with the file. Would it be possible to update your pwsh script to just download the msi file as part of the build just to test?

Should be a one liner 

`Invoke-RestMethod "https://www.7-zip.org/a/7z1900-x64.msi" -OutFile "$SourceFolder\$SetupFile"`

**Comment by malcolmardalon** [comment]
Looks like this was the case after all!  If I download the MSI as above it works.  Thank you for your speedy/helpful help!  Strange I thought using Git LFS would protect the integrity of the file.
