### ISSUE TITLE
Limited File size

### ISSUE THREAD

**Issue by rzander** [getsimeon/IntuneAppBuilder#8]
If the Intunewin File will be larger than 2GB , the tool breaks with the message:
`Unhandled exception: System.IO.IOException: Stream was too long.`

Root cause is the Function `EncryptFileAsync` which is using a MemoryStream to encrypt the file. 
MemoryStreams have a max size of 2GB, so any files larger than this size will fail...

If you replace the MemoryStream with a FileStream, it does work without problems.

**Comment by admin-simeon** [comment]
Thanks @rzander - we have deployed a new version of the package that includes this fix. It uses a `FileStream` that writes to a temp file and auto-deletes the file when the stream is disposed.
